cp_competition_tree:
    path:     /{id}/tree
    defaults: { _controller: CPCompetitionBundle:test:index }
cp_competition_new:
    path:     /new
    defaults: { _controller: CPCompetitionBundle:test:new }
cp_competition_game:
    path:     /{id}/game/{game_id}
    defaults: { _controller: CPCompetitionBundle:test:game }

