cp_competition_tree:
    path:     /{id}/tree
    defaults: { _controller: CPCompetitionBundle:BinaryTree:tree }
cp_competition_new:
    path:     /new
    defaults: { _controller: CPCompetitionBundle:CreateTournois:new }
cp_competition_gametree:
    path:     /{id}/gametree/{game_id}
    defaults: { _controller: CPCompetitionBundle:BinaryTree:game }
cp_competition_gameroundrobin:
    path:     /{id}/gameroundrobin/{game_id}
    defaults: { _controller: CPCompetitionBundle:RoundRobin:game }
cp_competition_roundrobinview:
    path:      /{id}/roundrobinview
    defaults: { _controller: CPCompetitionBundle:RoundRobin:view }
cp_competition_roundrobingenerate:
    path:      /{id}/roundrobingenerate
    defaults: { _controller: CPCompetitionBundle:RoundRobin:generate }
cp_competition_leagueview:
    path:      /{id}/leagueview
    defaults: { _controller: CPCompetitionBundle:League:view }
cp_competition_gameleague:
    path:     /{id}/gameleague/{game_id}
    defaults: { _controller: CPCompetitionBundle:League:game }
cp_competition_viewTournois:
    path:     /viewTournois
    defaults: { _controller: CPCompetitionBundle:RegisterTournois:view }
cp_competition_inscription:
    path:     /inscription/{id}
    defaults: { _controller: CPCompetitionBundle:RegisterTournois:inscription }
cp_competition_viewGames:
    path:     /viewGames
    defaults: { _controller: CPCompetitionBundle:ManageTournois:view }
cp_competition_uploadScreenshots:
    path:     /uploadScreenshots/{id}
    defaults: { _controller: CPCompetitionBundle:ManageTournois:uploadScreenshots }
cp_competition_validation:
    path:     /validation/{id}
    defaults: { _controller: CPCompetitionBundle:ManageTournois:validateScore }
cp_competition_viewPastGames:
    path:     /viewPastGames
    defaults: { _controller: CPCompetitionBundle:ManageTournois:viewPastGames }
cp_competition_adminViewGames:
    path:     /adminViewGames
    defaults: { _controller: CPCompetitionBundle:AdminManageTournois:adminViewGames }
cp_competition_viewMyTournois:
    path:     /viewMyTournois
    defaults: { _controller: CPCompetitionBundle:ManageTournois:myTournaments }
cp_competition_generateTournoi:
    path:     /{id}/generatetree
    defaults: { _controller: CPCompetitionBundle:ManageTournois:generate }