cp_competition_tree:
    path:     /{id}/tree
    defaults: { _controller: CPCompetitionBundle:BinaryTree:tree }
cp_competition_new:
    path:     /new
    defaults: { _controller: CPCompetitionBundle:BinaryTree:new }
cp_competition_gametree:
    path:     /{id}/gametree/{game_id}
    defaults: { _controller: CPCompetitionBundle:BinaryTree:game }
cp_competition_gameroundrobin:
    path:     /{id}/gameroundrobin/{game_id}
    defaults: { _controller: CPCompetitionBundle:RoundRobin:game }
cp_competition_roundrobinview:
    path:      /{id}/roundrobinview
    defaults: { _controller: CPCompetitionBundle:RoundRobin:view }
cp_competition_roundrobingenerate:
    path:      /{id}/roundrobingenerate
    defaults: { _controller: CPCompetitionBundle:RoundRobin:generate }
cp_competition_leagueview:
    path:      /{id}/leagueview
    defaults: { _controller: CPCompetitionBundle:League:view }
cp_competition_gameleague:
    path:     /{id}/gameleague/{game_id}
    defaults: { _controller: CPCompetitionBundle:League:game }

