cp_competition_tree:
    path:     /{id}/tree
    defaults: { _controller: CPCompetitionBundle:BinaryTree:tree }
cp_competition_new:
    path:     /new
    defaults: { _controller: CPCompetitionBundle:BinaryTree:new }
cp_competition_game:
    path:     /{id}/game/{game_id}
    defaults: { _controller: CPCompetitionBundle:BinaryTree:game }
cp_competition_viewTournois:
    path:     /viewTournois
    defaults: { _controller: CPCompetitionBundle:RegisterTournois:view }
cp_competition_inscription:
    path:     /inscription/{id}
    defaults: { _controller: CPCompetitionBundle:RegisterTournois:inscription }
cp_competition_viewGames:
    path:     /viewGames
    defaults: { _controller: CPCompetitionBundle:ManageTournois:view }
cp_competition_validation:
    path:     /validation/{id}
    defaults: { _controller: CPCompetitionBundle:ManageTournois:validateScore }
cp_competition_viewPastGames:
    path:     /viewPastGames
    defaults: { _controller: CPCompetitionBundle:ManageTournois:viewPastGames }