services:
  cp_competition.binarytree:
    class: CP\CompetitionBundle\TreeOperation\CPBinaryTree
    arguments: [@doctrine]
  cp_competition.roundrobin:
      class: CP\CompetitionBundle\RoundRobin\CPRoundRobin
      arguments: [@doctrine]