<?php

namespace CP\CompetitionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoundRobinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoundRobinRepository extends EntityRepository
{
}
