<?php

namespace CP\CompetitionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VersusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersusRepository extends EntityRepository
{
}
